from .common import *
from .military import *
from .military_communication import *
from .military_definition import *
from .root import *
from .communication import *
from .control import *
from .data import *
from .definition import *
from .object import *
from .struct import *
from .assignment import *
from .authority import *
from .condition import *
from .constraint import *
from .directive import *
from .event import *
from .interface import *
from .link import *
from .media import *
from .message import *
from .network import *
from .node import *
from .observation import *
from .organization import *
from .plan import *
from .property import *
from .protocol import *
from .record import *
from .state import *
from .activation import *
from .attribute import *
from .c3 import *
from .capability import *
from .command import *
from .cue import *
from .execution import *
from .gnc import *
from .health import *
from .identity import *
from .input import *
from .internal import *
from .isr import *
from .kinematic import *
from .lifecycle import *
from .military_organization import *
from .parameter import *
from .radio import *
from .relationship import *
from .resource import *
from .sensorstate import *
from .spatial import *
from .task import *
from .telemetry import *
from .validation import *
from .entities import *
from .mesh import *
from .military_radio import *
from .objective import *
from .payload import *
from .military_aerial import *
from .robot import *
from .uav import *
from .military_effects import *
from .military_entities import *
from .military_tasks import *

for _model in [obj for obj in list(globals().values()) if OCCIDModel in getattr(obj, "__mro__", ()) and obj is not OCCIDModel]:
    _model.model_rebuild(_types_namespace=globals())

__all__ = [name for name in globals() if not name.startswith("_")]
